### ISSUE TITLE
Replying to a nuked post results in a generic error

### ISSUE THREAD

**Issue by boarder2** [electroly/winchatty-server#1]
If you call postComment against a nuked post, the error object returned will be:

``` json
{"error":true,"code":"ERR_SERVER","message":"Unexpected response from server: <script type=\"text\/javascript\">\n alert( \"Error processing post: Trying to post to a nuked thread! \" );\n<\/script>\n"}
```

It would be nice if that was parsed and sent back as a known exception  ERR_NUKED or something.

**Comment by electroly** [comment]
Done in https://github.com/electroly/winchatty-server/commit/16cd146038658a219af78b5c4ae258fa087547ec.  ERR_NUKED is the new error.
