### ISSUE TITLE
Unread message count

### ISSUE THREAD

**Issue by boarder2** [electroly/winchatty-server#2]
It'd be sweet if we could get a count of unread SM's without having to get all the pages of SM's a user has.

POST v2/getUnreadMessageCount or something like that.

**Comment by electroly** [comment]
Should be easy.  I'll try to add this tonight.

**Comment by electroly** [comment]
Done in https://github.com/electroly/winchatty-server/commit/3cd44fb5d51143b68acab7299e53862559d5a97a.  The new call is /v2/getMessageCount and it returns both the total and unread counts.
